name: PHP

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, intl
          tools: composer:v2
      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress --no-suggest
        run: ./vendor/bin/phpstan ./app/Http/Controllers/PostController.php
        run: ./vendor/bin/phpcs ./app/Http/Controllers/PostController.php
